source='img/NOBLUE/custom_01.jpg';
out1='img/NOBLUE/alpha_custom_01.jpg';
out2='img/NOBLUE/matte_custom_01.jpg';
blueRef=[1,480];
img=im2double(imread(source));
BB=img(blueRef(1),blueRef(2),3);
alpha = noblue(img,BB);
matte=zeros(size(img));
matte(:,:,1)=img(:,:,1)+1-alpha;
matte(:,:,2)=img(:,:,2)+1-alpha;
matte(:,:,3)=1-alpha;
imwrite(alpha,out1);
imwrite(matte,out2);

source='img/NOBLUE/custom_02.jpg';
out1='img/NOBLUE/alpha_custom_02.jpg';
out2='img/NOBLUE/matte_custom_02.jpg';
blueRef=[1,320];
img=im2double(imread(source));
BB=img(blueRef(1),blueRef(2),3);
alpha = noblue(img,BB);
matte=zeros(size(img));
matte(:,:,1)=img(:,:,1)+1-alpha;
matte(:,:,2)=img(:,:,2)+1-alpha;
matte(:,:,3)=1-alpha;
imwrite(alpha,out1);
imwrite(matte,out2);

source='img/NOBLUE/custom_03.jpg';
out1='img/NOBLUE/alpha_custom_03.jpg';
out2='img/NOBLUE/matte_custom_03.jpg';
blueRef=[1,1];
img=im2double(imread(source));
BB=img(blueRef(1),blueRef(2),3);
alpha = noblue(img,BB);
matte=zeros(size(img));
matte(:,:,1)=img(:,:,1)+1-alpha;
matte(:,:,2)=img(:,:,2)+1-alpha;
matte(:,:,3)=1-alpha;
imwrite(alpha,out1);
imwrite(matte,out2);
